# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1055, 745)
        MainWindow.setStyleSheet("background-color: rgb(255, 239, 213)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.viewTable = QtWidgets.QPushButton(self.centralwidget)
        self.viewTable.setGeometry(QtCore.QRect(100, 130, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.viewTable.setFont(font)
        self.viewTable.setStyleSheet("background-color: rgb(176, 224, 230)")
        self.viewTable.setCheckable(False)
        self.viewTable.setObjectName("viewTable")
        self.addInformayionInTable = QtWidgets.QPushButton(self.centralwidget)
        self.addInformayionInTable.setGeometry(QtCore.QRect(100, 250, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.addInformayionInTable.setFont(font)
        self.addInformayionInTable.setStyleSheet("background-color: rgb(176, 224, 230)")
        self.addInformayionInTable.setObjectName("addInformayionInTable")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(900, 640, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.exit.setFont(font)
        self.exit.setStyleSheet("background-color: rgb(176, 224, 230)")
        self.exit.setObjectName("exit")
        self.removeInformationInTable = QtWidgets.QPushButton(self.centralwidget)
        self.removeInformationInTable.setGeometry(QtCore.QRect(100, 370, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.removeInformationInTable.setFont(font)
        self.removeInformationInTable.setStyleSheet("background-color: rgb(176, 224, 230)")
        self.removeInformationInTable.setObjectName("removeInformationInTable")
        self.updateInformationInTable = QtWidgets.QPushButton(self.centralwidget)
        self.updateInformationInTable.setGeometry(QtCore.QRect(100, 490, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.updateInformationInTable.setFont(font)
        self.updateInformationInTable.setStyleSheet("background-color: rgb(176, 224, 230)")
        self.updateInformationInTable.setObjectName("updateInformationInTable")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 130, 460, 460))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("png/pngegg (1).png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 30, 831, 71))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(33)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главная страница"))
        self.viewTable.setText(_translate("MainWindow", "Показать данные"))
        self.addInformayionInTable.setText(_translate("MainWindow", "Добавить данные в таблицу"))
        self.exit.setText(_translate("MainWindow", "Выход"))
        self.removeInformationInTable.setText(_translate("MainWindow", "Удалить данные из таблицы"))
        self.updateInformationInTable.setText(_translate("MainWindow", "Обноавить данные в таблице"))
        self.label_2.setText(_translate("MainWindow", "Аэропорт"))
