# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowThisTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1055, 745)
        MainWindow.setStyleSheet("background-color: rgb(255, 239, 213)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(890, 630, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.back.setFont(font)
        self.back.setStyleSheet("background-color: rgb(176, 224, 230)")
        self.back.setObjectName("back")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 30, 1061, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.info_about_client = QtWidgets.QPushButton(self.centralwidget)
        self.info_about_client.setGeometry(QtCore.QRect(50, 220, 951, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.info_about_client.setFont(font)
        self.info_about_client.setStyleSheet("background-color: rgb(176, 224, 230)")
        self.info_about_client.setObjectName("info_about_client")
        self.inf_about_pilot = QtWidgets.QPushButton(self.centralwidget)
        self.inf_about_pilot.setGeometry(QtCore.QRect(50, 370, 951, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.inf_about_pilot.setFont(font)
        self.inf_about_pilot.setStyleSheet("background-color: rgb(176, 224, 230)")
        self.inf_about_pilot.setObjectName("inf_about_pilot")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Таблица с данными"))
        self.back.setText(_translate("MainWindow", "Назад"))
        self.label.setText(_translate("MainWindow", "Данные"))
        self.info_about_client.setText(_translate("MainWindow", "Информация о пассажирах, их место, откуда и куда пассажир летит"))
        self.inf_about_pilot.setText(_translate("MainWindow", "Информация о самолете и пилоте"))
